# R8 rules for anything that depends on this plugin — the app module picks them
# up automatically, which matters because `src-tauri/gen/` is regenerated by
# `tauri android init` and cannot hold rules of its own.
#
# Only release builds run R8, so none of this is exercised by `ci.yml`, which
# builds Android with --debug. `release.yml` is what proves it.

# androidx.security:security-crypto is implemented over Google Tink, which is
# compiled against JSR-305 annotations that are deliberately not shipped at
# runtime: javax.annotation.Nullable and javax.annotation.concurrent.GuardedBy.
# R8 treats the dangling references as an error and fails the build.
#
# The annotations carry no runtime behaviour and nothing reflects over them, so
# silencing the warning is the entire fix. Adding the JSR-305 artifact as a real
# dependency would also work, at the cost of shipping classes we never use.
-dontwarn javax.annotation.**

# Tink resolves key managers and key templates by name through a registry, and
# its shaded protobuf messages are reflected over as well, so neither survives
# being renamed. This is deliberately broad: getting it wrong breaks
# EncryptedSharedPreferences at runtime, in release builds only, on a device —
# somewhere no test in this repository can reach. A few hundred kilobytes is
# the right price for that.
-keep class com.google.crypto.tink.** { *; }
-dontwarn com.google.crypto.tink.**
